apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hrrbkkurf-nodejs
  janus-idp.io/tekton: hrrbkkurf-nodejs
  backstage.io/kubernetes-id: hrrbkkurf-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hrrbkkurf-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
